name: HiveDB
version: 0.1.0.0
github: "githubuser/HiveDB"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2023 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/HiveDB#readme>

dependencies:
  #  common
  - base >= 4.7 && < 5
  - scotty
  - text
  - time
  - http-types
  - wai
  - dotenv
  - scotty-login-session
  # frontend
  - template-haskell
  - shakespeare
  - blaze-html
  - blaze-markup
  - scotty-cookie
  - heterocephalus
  - cookie
  # backend
  - aeson
  - hedis
  - bytestring
  - unordered-containers
  - containers
  - split

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  HiveDB-frontend:
    main: Main.hs
    source-dirs: frontend-server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HiveDB

  HiveDB-backend:
    main: Main.hs
    source-dirs: backend-server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HiveDB

tests:
  HiveDB-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HiveDB
